-- seed_equipment.sql
-- Generated from user's CSV inventory
-- Run this in Supabase SQL editor to populate the `equipment` table

INSERT INTO equipment (id, name, total_qty, available_qty, metadata) VALUES
  (gen_random_uuid(), 'FX3', 5, 5, '{"category":"الكاميرات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'sony a7', 5, 5, '{"category":"الكاميرات","condition":"جيدة جداً","notes":"مشكلة الحرارة"}'::jsonb),
  (gen_random_uuid(), 'Osmo Pockrt 3', 12, 12, '{"category":"الكاميرات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'GoPro 11', 2, 2, '{"category":"الكاميرات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'GoPro 12', 3, 3, '{"category":"الكاميرات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), '70-200', 2, 2, '{"category":"العدسات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), '85 prime', 2, 2, '{"category":"عدسات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), '24-70', 3, 3, '{"category":"عدسات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), '16-35', 3, 3, '{"category":"عدسات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), '12-24', 3, 3, '{"category":"عدسات","condition":"لا يوجد تقرير","notes":"في الصيانة"}'::jsonb),
  (gen_random_uuid(), 'ريدر', 10, 10, '{"category":"تخزين","condition":"جيدة","notes":"لا يمكن قرائة ميموري الكاميرا"}'::jsonb),
  (gen_random_uuid(), 'ذواكر مايكرو 128 قيقا', 10, 10, '{"category":"تخزين","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'ذواكر مايكرو صوت', 13, 13, '{"category":"تخزين","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'ذواكر كاميرا 320 قيقا', 12, 12, '{"category":"تخزين","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'ذواكر كاميرا 1 تيرا', 1, 1, '{"category":"تخزين","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'ذواكر كاميرا 160 قيقا', 2, 2, '{"category":"تخزين","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'شدقن مايك', 9, 9, '{"category":"صوتيات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'مايك DJI', 14, 14, '{"category":"صوتيات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'تاس كام', 32, 32, '{"category":"صوتيات","condition":"جيدة جداً","notes":"تم استهلاكها مما يسبب تقطع في الصوت"}'::jsonb),
  (gen_random_uuid(), 'جلدة تاس كام', 12, 12, '{"category":"صوتيات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'بطارية مونيتر', 4, 4, '{"category":"شاحن","condition":"ممتازة","notes":"لا يوجد شاحن لها"}'::jsonb),
  (gen_random_uuid(), 'شواحن قو برو', 6, 6, '{"category":"شاحن","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'بطاريات كاميرا', 30, 30, '{"category":"شاحن","condition":"ممتازة","notes":"واحدة من البطاريات غير اصلية"}'::jsonb),
  (gen_random_uuid(), 'شواحن بطاريات كاميرا', 13, 13, '{"category":"شاحن","condition":"جيدة","notes":"يوجد منفذين ولا يعمل الى منفذ واحد"}'::jsonb),
  (gen_random_uuid(), 'godox SL300R', 6, 6, '{"category":"اضائة","condition":"ممتازة","notes":"قزاز الاضائة مكسور"}'::jsonb),
  (gen_random_uuid(), 'سوفت بوكس', 7, 7, '{"category":"اضائة","condition":"تالفة","notes":"مكسورة ولا يمكن اصلاحها"}'::jsonb),
  (gen_random_uuid(), 'فلاش تصوير', 1, 1, '{"category":"اضائة","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'اضائة فوق الكام', 2, 2, '{"category":"اضائة","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'اضائة مسرح', 2, 2, '{"category":"اضائة","condition":"جيدة","notes":"سلك الكهرب تالف"}'::jsonb),
  (gen_random_uuid(), 'عاكس اضائة', 1, 1, '{"category":"اضائة","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'تيوب لايت', 11, 11, '{"category":"اضائة","condition":"جيدة","notes":"الشاشة مكسورة"}'::jsonb),
  (gen_random_uuid(), 'استاند كاميرا', 16, 16, '{"category":"استاند","condition":"جيدة","notes":"لا يوجد بليت لتثبيت الكاميرا"}'::jsonb),
  (gen_random_uuid(), 'سي استاند', 8, 8, '{"category":"استاند","condition":"جيدة","notes":"لا يمكن التحكم في الطول"}'::jsonb),
  (gen_random_uuid(), 'ارم سي استاند', 6, 6, '{"category":"استاند","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'استاند اضائة', 13, 13, '{"category":"استاند","condition":"جيدة","notes":"لا يمكن التحكم في الطول"}'::jsonb),
  (gen_random_uuid(), 'استاند خلفية', 1, 1, '{"category":"استاند","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'وزن سي استاند', 8, 8, '{"category":"استاند","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'حامل كاميرا صغير', 6, 6, '{"category":"استاند","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'شنطة نقل معدات وسط', 1, 1, '{"category":"الشنط","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'شنطة نقل معدات صغير', 1, 1, '{"category":"الشنط","condition":"جيدة","notes":"لا يوجد مقسم مما يسبب تكسر في المعدات"}'::jsonb),
  (gen_random_uuid(), 'شنطة نقل معدات طويل', 3, 3, '{"category":"الشنط","condition":"جيدة","notes":"لا يوجد مقسم لها"}'::jsonb),
  (gen_random_uuid(), 'شنطة نقل معدات كبير', 2, 2, '{"category":"الشنط","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'خلفية خضراء', 1, 1, '{"category":"اكسسوارات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'خلفية رصاصية', 1, 1, '{"category":"اكسسوارات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'سماعات تواصل', 9, 9, '{"category":"اكسسوارات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'فيست', 2, 2, '{"category":"اكسسوارات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'مجموعة مفكات', 2, 2, '{"category":"اكسسوارات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'ND filter', 6, 6, '{"category":"اكسسوارات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'ND filter cinematic', 3, 3, '{"category":"اكسسوارات","condition":"ممتازة","notes":"تم طلبها بالخطأ ولن يتم استخدامها ابداً"}'::jsonb),
  (gen_random_uuid(), 'بكج اكسسوارات قو برو', 12, 12, '{"category":"اكسسوارات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'مثبت اوزمو للسيارة', 5, 5, '{"category":"اكسسوارات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'مثبت اوزمو شباصه', 1, 1, '{"category":"اكسسوارات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'مثبت اوزمو في الحديد', 8, 8, '{"category":"اكسسوارات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'استاند مثبت قو برو', 5, 5, '{"category":"اكسسوارات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'منظف العدة', 2, 2, '{"category":"اكسسوارات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'مونيتر', 5, 5, '{"category":"اكسسوارات","condition":"لا يوجد تقرير","notes":"لم يتم استخدامها ابداً"}'::jsonb),
  (gen_random_uuid(), 'رونين مانع اهتزاز', 2, 2, '{"category":"اكسسوارات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'توصيلة رول', 4, 4, '{"category":"موصلات","condition":"ممتازة","notes":""}'::jsonb),
  (gen_random_uuid(), 'توصيلة', 5, 5, '{"category":"موصلات","condition":"تالفة","notes":""}'::jsonb),
  (gen_random_uuid(), 'اضائة سوفت بوكس 200', 2, 2, '{"category":"اضائة","condition":"جيدة","notes":"مكسورة الاذرع"}'::jsonb),
  (gen_random_uuid(), 'اضائة سوفت بوكس 150', 2, 2, '{"category":"اضائة","condition":"تالفة","notes":"منفذ الفيش مخلوع"}'::jsonb),
  (gen_random_uuid(), 'اضائة p60', 1, 1, '{"category":"اضائة","condition":"جيدة","notes":"لا يوجد سلك + الشاشة مكسورة"}'::jsonb),
  (gen_random_uuid(), 'عدة صوت', 1, 1, '{"category":"صوتيات","condition":"لا يوجد تقرير","notes":"لم يتم استخدامها ابداً"}'::jsonb)
;

-- End of seed file
